local utils = require('utils')

utils.map('n', '<Leader>gs', '<cmd>Git<CR>')
utils.map('n', '<Leader>gps', '<cmd>:Dispatch! Git push<CR>')
utils.map('n', '<Leader>gpl', '<cmd>:Dispatch! Git pull<CR>')
utils.map('n', '<Leader>gd', '<cmd>Gvdiffsplit<CR>')
utils.map('n', '<Leader>ga', '<cmd>Git fetch --all<CR>')
utils.map('n', '<Leader>grc', '<cmd>Git rebase --continue<CR>')
utils.map('n', '<Leader>grum', '<cmd>Git rebase upstream/master<CR>')
utils.map('n', '<Leader>grom', '<cmd>Git rebase origin/master<CR>')
utils.map('n', '<Leader>gdr', '<cmd>diffget //3<CR>')
utils.map('n', '<Leader>gf', '<cmd>diffget //3<CR>')
utils.map('n', '<Leader>gdl', '<cmd>diffget //2<CR>')
utils.map('n', '<Leader>gj', '<cmd>diffget //2<CR>')
utils.map('n', '<leader>gc', '<cmd>lua require("config.telescope").git_branches()<CR>')
utils.map('n', '<leader>g-', '<cmd>:Silent Git stash<CR>')
utils.map('n', '<leader>g+', '<cmd>:Silent Git stash pop<CR>')
utils.map('n', '<leader>gh', '<cmd>0Gclog<CR>')

